    name: "Audit log recording"
    on:
      issues:
        types: [opened, edited]
    jobs:
        audit-log-recording:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v3
            - name: Echo issue name
              run: echo ${{ github.event.issue.title }}
